version: '3'

services:

  sphinx:
    image: macbre/sphinxsearch
    ports:
      - '9308:9306'
    volumes:
      - './data/sphinx:/opt/sphinx/index:delegated'
      - './conf/sphinx.conf:/opt/sphinx/conf/sphinx.conf'
    networks:
      - zfe

  mysql:
    image: 'mysql:5.6'
    ports:
      - '3308:3306'
    # user: '1000' # somebody from host machine to prevents messing up permission on /data/mysql volume
    volumes:
      - './conf/mysql/my.cnf:/etc/mysql/conf.d/z.cnf'
      - './conf/mysql/initial.sql:/docker-entrypoint-initdb.d/initial.sql'
      - './data/mysql:/var/lib/mysql:delegated'
    env_file:
      - .env.mysql
    networks:
      - zfe
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  phpfpm:
    depends_on:
      - mysql
      - sphinx
    build:
      context: ./src
    volumes:
      - './data/app:/var/www/data:delegated'
      - './src:/var/www/html:cached'
      - './conf/php.ini:/usr/local/etc/php/conf.d/extra.ini'
    environment:
      - SPHINX_HOST=sphinx
      - SPHINX_PORT=9306
    env_file:
      - .env.mysql
    networks:
      - zfe

  web:
    depends_on:
      - phpfpm
    image: 'nginx:latest'
    ports:
      - '8000:80'
    volumes:
      - './conf/server.conf:/etc/nginx/conf.d/default.conf'
      - './src/public:/var/www/html/public:cached'
    networks:
      - zfe

networks:
  zfe:
