version: '3'
services:
  sphinx:
    image: macbre/sphinxsearch
    user: '1000' # somebody from host machine to prevents messing up permission on /data/mysql volume
    volumes:
      - './data/sphinx:/opt/sphinx/index:delegated'
      - './conf/sphinx.conf:/opt/sphinx/conf/sphinx.conf'
  mysql:
    image: 'mysql:5.6'
    user: '1000' # somebody from host machine to prevents messing up permission on /data/mysql volume
    volumes:
      - './conf/my.cnf:/etc/mysql/conf.d/z.cnf'
      - './data/mysql:/var/lib/mysql:delegated'
      - './src/assets/initial.sql:/docker-entrypoint-initdb.d/intial.sql'
    environment:
      - MYSQL_DATABASE=zfe
      - MYSQL_USER=zfe
      - MYSQL_PASSWORD=zfe
      - MYSQL_ROOT_PASSWORD=toor
  php:
    depends_on:
      - mysql
      - sphinx
    build: .
    user: '1000' # somebody from host machine to prevents messing up permission on /data/mysql volume
    volumes:
      - './data/app:/var/www/data:delegated'
      - './src:/var/www/html:cached'
      - './conf/php.ini:/usr/local/etc/php/conf.d/extra.ini'
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=zfe
      - DB_PASSWORD=zfe
      - DB_DATABASE=zfe
      - SPHINX_HOST=sphinx
      - SPHINX_PORT=9306
  web:
    depends_on:
      - php
    image: 'nginx:latest'
    ports:
      - '8000:80'
    links:
      - php
    volumes:
      - './conf/server.conf:/etc/nginx/conf.d/default.conf'
      - './src/public:/var/www/html/public:cached'
