version: '3'

services:

  sphinx:
    image: macbre/sphinxsearch
    ports:
      - '9308:9306'
    volumes:
      - './data/sphinx:/opt/sphinx/index:delegated'
      - './src/assets/sphinx/sphinx.conf:/opt/sphinx/conf/sphinx.conf'
    networks:
      - zfe

  mysql:
    image: 'mysql:5.6'
    ports:
      - '3308:3306'
    # user: '1000' # somebody from host machine to prevents messing up permission on /data/mysql volume
    volumes:
      - './conf/mysql/my.cnf:/etc/mysql/conf.d/z.cnf'
      - './conf/mysql/initial.sql:/docker-entrypoint-initdb.d/initial.sql'
      - './data/mysql:/var/lib/mysql:delegated'
    env_file:
      - .env.mysql
    networks:
      - zfe
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  phpfpm:
    depends_on:
      - mysql
      - sphinx
    build:
      context: ./src
    volumes:
      - './data/app:/var/www/data:delegated'
      - './src:/var/www/html:cached'
      - './conf/php.ini:/usr/local/etc/php/conf.d/extra.ini'
    environment:
      - APPLICATION_ENV=development
      - SPHINX_HOST=sphinx
      - SPHINX_PORT=9306
    env_file:
      - .env.mysql
    networks:
      - zfe

  web:
    depends_on:
      - phpfpm
    image: 'nginx:latest'
    ports:
      - '8000:80'
    volumes:
      - './conf/server.conf:/etc/nginx/conf.d/default.conf'
      - './src/public:/var/www/html/public:cached'
    networks:
      - zfe

  tests:
    depends_on:
      - web
    build:
      context: ./tests
    volumes:
      - './tests:/var/www/tests'
      - './src:/var/www/src'
      - './conf/php.ini:/usr/local/etc/php/conf.d/extra.ini'
    environment:
      - APPLICATION_ENV=testing
    env_file:
      - .env.mysql
    networks:
      - zfe

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    container_name: es01
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - zfe

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    container_name: es02
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata02:/usr/share/elasticsearch/data
    networks:
      - zfe

  kibana:
    depends_on:
      - es01
      - es02
    image: docker.elastic.co/kibana/kibana:7.3.1
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://es01:9200
    ports:
      - 5601:5601
    networks:
      - zfe

networks:
  zfe:

volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local
